# Generated by Django 3.2.3 on 2021-05-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
