# Generated by Django 3.2.3 on 2021-05-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventso', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
